name: native_extension_with_build_tools
version: 0.0.12
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Example of the `build script` for the native extension (C++) for the Dart VM with the usage of `build_tools` and `ccompilers`.
homepage: https://github.com/mezoni/native_extension_with_build_tools
dependencies:
  build_tools: any
  ccompilers: any
  file_utils: any
  patsubst:
    git: https://github.com/mezoni/patsubst.git
